# 头部菜单，title: link
menu:
  关于: /whoami
  归档: /archives
  博客: http://blog.jonsam.site
  Github: https://github.com/jonsam-ng

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3:
  - https://link.hhtjim.com/163/518587919.mp3
  - https://link.hhtjim.com/163/1320530720.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# 网站关键字
keywords: jonsam, diary

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
