# 头部菜单，title: link
menu:
  关于: /whoami
  归档: /archives
  博客: http://blog.jonsam.site
  Github: https://github.com/jonsam-ng

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3:
  - https://link.hhtjim.com/163/518587919.mp3
  - https://link.hhtjim.com/163/1320530720.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否自动展开评论框
  autoExpand: true
  # 应用编号
  clientID: "ef144378d85106f38c0f"
  # 应用秘钥
  clientSecret: "3024558d3d3d12c074d774a73c8178ce2f790f17"
  # issue仓库名
  repo: "jonsam-ng.github.io"
  # Github名
  owner: "jonsam-ng"
  # Github名
  admin: ["jonsam-ng"]
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: true

# 网站关键字
keywords: Jonsam

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.ico

# rss文件
rss: atom.xml
